/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnosticos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Historial */
        get: operations["listar_historial_api_v1_diagnosticos_get"];
        put?: never;
        /** Crear Diagnostico */
        post: operations["crear_diagnostico_api_v1_diagnosticos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnosticos/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear Diagnosticos Lote */
        post: operations["crear_diagnosticos_lote_api_v1_diagnosticos_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnosticos/{diagnostico_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Diagnostico */
        get: operations["obtener_diagnostico_api_v1_diagnosticos__diagnostico_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Catalogo */
        get: operations["listar_catalogo_api_v1_catalogo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Enfermedad */
        get: operations["obtener_enfermedad_api_v1_catalogo__codigo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imagenes/{nombre_archivo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Imagen */
        get: operations["obtener_imagen_api_v1_imagenes__nombre_archivo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_crear_diagnostico_api_v1_diagnosticos_post */
        Body_crear_diagnostico_api_v1_diagnosticos_post: {
            /** Imagen */
            imagen: string;
            /** @default hoja */
            organo: components["schemas"]["Organo"];
        };
        /** Body_crear_diagnosticos_lote_api_v1_diagnosticos_batch_post */
        Body_crear_diagnosticos_lote_api_v1_diagnosticos_batch_post: {
            /** Imagenes */
            imagenes: string[];
            /** @default hoja */
            organo: components["schemas"]["Organo"];
        };
        /** CajaSchema */
        CajaSchema: {
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
            /** X2 */
            x2: number;
            /** Y2 */
            y2: number;
        };
        /** DeteccionSchema */
        DeteccionSchema: {
            /** Clase */
            clase: string;
            /** Confianza */
            confianza: number;
            caja: components["schemas"]["CajaSchema"];
        };
        /** DiagnosticoResponse */
        DiagnosticoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            organo: components["schemas"]["Organo"];
            /** Propietario Id */
            propietario_id: string;
            /** Es Sano */
            es_sano: boolean;
            /** Enfermedades */
            enfermedades: string[];
            /** Detecciones */
            detecciones: components["schemas"]["DeteccionSchema"][];
            /** Imagen Url */
            imagen_url: string;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** DiagnosticosBatchResponse */
        DiagnosticosBatchResponse: {
            /** Diagnosticos */
            diagnosticos: components["schemas"]["DiagnosticoResponse"][];
            /** Total */
            total: number;
            /** Total Enfermos */
            total_enfermos: number;
            /** Total Sanos */
            total_sanos: number;
        };
        /** EnfermedadResponse */
        EnfermedadResponse: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Organo */
            organo: string;
            /** Severidad */
            severidad: string;
            /** Descripcion */
            descripcion: string;
            /** Sintomas */
            sintomas: string[];
            /** Recomendaciones */
            recomendaciones: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Organo
         * @enum {string}
         */
        Organo: "hoja" | "fruto";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    listar_historial_api_v1_diagnosticos_get: {
        parameters: {
            query?: {
                limite?: number;
                desplazamiento?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_diagnostico_api_v1_diagnosticos_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_crear_diagnostico_api_v1_diagnosticos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_diagnosticos_lote_api_v1_diagnosticos_batch_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_crear_diagnosticos_lote_api_v1_diagnosticos_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticosBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_diagnostico_api_v1_diagnosticos__diagnostico_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                diagnostico_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_catalogo_api_v1_catalogo_get: {
        parameters: {
            query?: {
                organo?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnfermedadResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_enfermedad_api_v1_catalogo__codigo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnfermedadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_imagen_api_v1_imagenes__nombre_archivo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nombre_archivo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
